#redis(分片)
spring:
  redis:
    host: 10.11.103.234
    port: 6379
    password:                 # Redis服务器连接密码（默认为空）
    database: 0               # Redis数据库索引（默认为0） 用命令切换select 1
    pool:
      max-active: 8           # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1            # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 500           # 连接池中的最大空闲连接
      min-idle: 0             # 连接池中的最小空闲连接
    timeout: 0

