server:
  port: 8081
#  要用maven替换不再使用${},而是使用@..@代替
app:
  name: @log.test@

#引用该文件下其他变量还是使用${}
spring:
  application:
    name: maven-env-sample1
  jmx:
    default-domain: ${spring.application.name}

